---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  domain: "%{hiera('domain')}"

  zone_id: "%{hiera('public_zone_id')}"

  mail_from_domain: "%{hiera('mail_from_domain')}"
