---
configuration_directory: "%{cwd}/spec/unit/infra/root"
state_file: "%{cwd}/state/root.tfstate"
vars:
  region: "%{hiera('region')}"

  domain: "%{hiera('domain')}"

  zone_id: "%{hiera('public_zone_id')}"
